# general settings
model_configs_path: model_configs.json
project_name: job_seeking
round_n: 2
distributed: true
save_dir: 
embedding_api: http://localhost:8000/
load_simulator_path: 
host: localhost
base_port: 12000

# custom settings
seeker_agent_configs_path: seeker_agent_configs.json
interviewer_agent_configs_path: interviewer_agent_configs.json
company_agent_configs_path: company_agent_configs.json
pool_size: 10
