# general settings
model_configs_path: model_configs.json
project_name: job_seeking
round_n: 1
save_dir: 
embedding_api: http://localhost:8002/
load_simulator_path: 
host: localhost
base_port: 13000
server_num_per_host: 200

# custom settings
seeker_agent_configs_path: seeker_agent_configs.json
interviewer_agent_configs_path: interviewer_agent_configs.json
pool_size: 10
