# general settings
model_configs_path: "model_configs.json"  
project_name: "job_seeking"
round_n: 2

# custom settings
seeker_agent_configs_path: "seeker_agent_configs.json"
job_agent_configs_path: "job_agent_configs.json"
company_agent_configs_path: "company_agent_configs.json"
emb_model_path: "Downloads/DAM-bert_base-mlm-dureader"
adapter_path: "Downloads/REM-bert_base-dense-distil-dureader"
restore_file_path: 
gpu: 0
make_decision_round_n: 2
pool_size: 3
excess_cv_passed_n: 2
wl_n: 2
