# general settings
model_configs_path: model_configs.json
project_name: job_seeking
round_n: 1
save_dir:
embedding_api: [
  http://localhost:8666, 
  http://localhost:8667,
  http://localhost:8668,
  http://localhost:8669
]
load_simulator_path: 
host: localhost
port: 13000
gpu_id: 5

# custom settings
seeker_agent_configs_path: SeekerAgent_configs.json
interviewer_agent_configs_path: InterviewerAgent_configs.json
pool_size: 10
