# general settings
model_configs_path: model_configs.json
project_name: recommendation
round_n: 2
embedding_api: [
  http://localhost:8666, 
  http://localhost:8667,
  http://localhost:8668,
  http://localhost:8669
]
load_simulator_path: 
host: localhost
base_port: 13000
server_num_per_host: 90
runtime_id: 

# custom settings
recuser_agent_configs_path: RecUserAgent_configs.json
item_infos_path: item_infos.json