# general settings
model_configs_path: model_configs.json
project_name: recommendation
round_n: 1
save_dir: 
embedding_api: http://localhost:8666/
load_simulator_path: 
host: localhost
base_port: 13000
server_num_per_host: 200

# custom settings
recuser_agent_configs_path: recuser_agent_configs.json
