# general settings
model_configs_path: model_configs.json
project_name: recommendation
round_n: 2
embedding_api: [http://localhost:8666]
host: localhost
base_port: 16000
server_num_per_host: 10
load_simulator_path:
runtime_id:

# custom settings
agent_configs_paths:
  RecUserAgent: RecUserAgent_configs.json
item_infos_path: item_infos.json
